accounts/urls.py
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from jobsapp.views import EditProfileView
from .views import *
from . import views

app_name = "accounts"

urlpatterns = [
    path('employee/register', RegisterEmployeeView.as_view(), name='employee-register'),
    path('employer/register', RegisterEmployerView.as_view(), name='employer-register'),
    path('employee/profile/update', EditProfileView.as_view(), name='employer-profile-update'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('login', LoginView.as_view(), name='login'),
    path('about/', views.about, name='about'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobsapp.urls')),
    path('', include('accounts.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %} {% endblock %} - Django Jobs</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Google fonts - Roboto for copy, Montserrat for headings-->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,700">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Montserrat:400,700">
    <!-- owl carousel-->
    <link rel="stylesheet" href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block styles %}{% endblock %}
    <!-- Favicon-->
    <link rel="shortcut icon" href="favicon.png">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>

<body>
    <!-- navbar-->
    <header class="header">
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a href="/" class="navbar-brand">
                    <img src="{% static 'img/logo-small.png' %}" alt="logo" class="d-none d-lg-block">
                    <span class="sr-only">Home</span>
                </a>
                <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler navbar-toggler-right">Menu<i class="fa fa-bars"></i>
                </button>
                <div id="navbarSupportedContent" class="collapse navbar-collapse">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a href="/" class="nav-link">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">Contact</a>
                        </li>
                        {% if request.user.is_authenticated and request.user.role == 'employer' %}
                        <li class="nav-item dropdown">
                            <a id="clientZone" href="#" data-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false"
                                class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
                                <div class="client-menu-image">
                                    <div class="inner">
                                        <img src="{% static 'img/company-1.png' %}" alt="company image"
                                            class="img-fluid">
                                    </div>
                                </div>
                                {% if request.user.role == 'employee' %}
                                {{ request.user.first_name }} {{ request.user.last_name }}
                                {% else %}
                                {{ request.user.first_name }}
                                {% endif %}
                            </a>
                            <div aria-labelledby="clientZone" class="dropdown-menu">
                                <a href="{% url 'jobs:employer-dashboard' %}" class="dropdown-item">Dashboard</a>
                                <a href="{% url 'jobs:employer-all-applicants' %}" class="dropdown-item">Applicants </a>
                                <a href="{% url 'jobs:employer-jobs-create' %}" class="dropdown-item">Post a new
                                    job </a>
                                <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                        {% elif request.user.is_authenticated and request.user.role == 'employee' %}
                        <li class="nav-item dropdown">
                            <a id="clientZone" href="#" data-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false"
                                class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
                                <div class="client-menu-image">
                                    <div class="inner">
                                        <img src="{% static 'img/company-1.png' %}" alt="company image"
                                            class="img-fluid">
                                    </div>
                                </div>
                                {% if request.user.role == 'employee' %}
                                {{ request.user.first_name }} {{ request.user.last_name }}
                                {% else %}
                                {{ request.user.first_name }}
                                {% endif %}
                            </a>
                            <div aria-labelledby="clientZone" class="dropdown-menu">
                                <a href="{% url 'accounts:employer-profile-update' %}" class="dropdown-item">Edit
                                    Profile</a>
                                <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                        {% else %}
                        <li class="nav-item dropdown">
                            <a id="pages" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                class="nav-link dropdown-toggle"><i class="fa fa-signing"></i>Register
                            </a>
                            <div aria-labelledby="pages" class="dropdown-menu">
                                <a href="{% url 'accounts:employee-register' %}" class="dropdown-item">Employee</a>
                                <a href="{% url 'accounts:employer-register' %}" class="dropdown-item">Employers</a>
                            </div>
                        </li>
                        <li class="nav-item" style="color: #fff">
                            <a href="{% url 'accounts:login' %}" class="btn navbar-btn btn-outline-light mb-5 mb-lg-0">
                                <i class="fa fa-sign-in"></i>Login
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        {% if messages %}

        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {# <li{% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</li>#}
            {% endfor %}

            {% endif %}
            {% block content %} {% endblock %}
    </div>
    <footer class="footer">
        <div class="footer__block">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-12 mb-5">
                        <h4 class="h5">About Jobs</h4>
                        <p> Welcome to <strong>Online Job Portal</strong> — your trusted platform for connecting
                            talented professionals with top employers.
                            Our goal is to make job searching and recruitment easy, efficient, and accessible to
                            everyone.

                            Whether you're a job seeker exploring new opportunities or an employer looking to hire top
                            talent,
                            Online Job Portal provides the tools you need to succeed. With a wide range of job listings,
                            smart filtering,
                            and a user-friendly interface, we aim to simplify the hiring process from start to finish.

                            Join thousands of users who rely on us to build their careers and grow their teams. Your
                            future starts here.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer__copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 text-md-left text-center">
                        <p>&copy;2019 Jobs</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"></script>
    <script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>

    {% block javascripts %}{% endblock %}

</body>

</html>